### ISSUE TITLE
The inventory plugin hard codes ansible_connection

### ISSUE THREAD

**Issue by MKletz** [kubevirt/kubevirt.core#33]
##### SUMMARY
[This](https://github.com/kubevirt/kubevirt.core/blob/6a7192ff7f7368cc3d54f975295a28ce23dc52bd/plugins/inventory/kubevirt.py#L514) line hard codes ansible_connection to be "ssh". While this works in many cases it also breaks support for Windows VMs without many options for workarounds since this is a host fact. It should be noted as well that just having it smart enough to replace "ssh" with "winrm" alone will not suffice ansible_host is also just using the IP address and winrm needs FQDN.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.15.5]
  config file = None
  configured module search path = ['/Users/mkletz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.5.0_1/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/mkletz/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/Cellar/ansible/8.5.0_1/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
1.1.0
```

##### STEPS TO REPRODUCE
Have a Windows VM exist

##### EXPECTED RESULTS
Be able to omit or customize these host facts

##### ACTUAL RESULTS
Cannot omit or customize these host facts

**Comment by 0xFelix** [comment]
Adding an option to use WinRM instead of SSH is relatively simple, but the FQDN requirement 
might be a bit problematic. Getting the FQDN of a VM is tricky, because you cannot simply ask 
the guest OS for its configured FQDN. (at least there is no way I know of right now, please correct me)

You may be able to construct the FQDN for the VM from its name and a static suffix,
but there is no guarantee it will match the configuration inside the guest OS.

kubesecondarydns may be able to help you, but it constructs FQDNs in an opinionated way,
which the guest OS would have to match in its configuration again.

The original collection kubevirt.core is based on (community.kubevirt) did have a feature,
 where user-defined variables could be provided by an annotation whose value is set
to a JSON encoded string of variables.

We could add this feature again, I'm just not sure if we should go with the previous approach or
instead go with a 1:1 mapping between each annotation having a prefix of 'ansible_'.

Regardless of the approach, should there be a set of reserved variables, which cannot be set 
from annotations or would you expect to be able to provide values for any variable?

**Comment by MKletz** [comment]
"You may be able to construct the FQDN for the VM from its name and a static suffix,
but there is no guarantee it will match the configuration inside the guest OS."
I was picturing the user providing this in the plug-in configuration. See the [VMware plug-in](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_inventory_inventory.html) as an example
![image](https://github.com/kubevirt/kubevirt.core/assets/28571284/fb89b8b2-72ed-40c0-a045-53513852e731)
There wouldn't be anything stopping the user (to my knowledge) from configuring the plugin multiple times scoped to different namespaces if there are differences in how to predict the fqdn.

I think a subset of protected variables would be expected. But typically more flexibility the better. The vmware inventory approach could be the way to go where we allow for the user to map/construct values from lables or annotations.
